version: 0.0
os: linux
files:
  - source: target/hello-word-jar-type-1.0.0.jar
    destination: /home/ec2-user/apps/addition-service
hooks:
  AfterInstall:
    - location: change-file-permission.sh
      runas: root
  ApplicationStart:
    - location: start-addition-service.sh
      runas: root