version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/apps/hello-word
hooks:
  AfterInstall:
    - location: change-file-permission.sh
      runas: root
  ApplicationStart:
    - location: start-addition-service.sh
      runas: root