version: 0.0
os: linux
files:
  - source: ./change-file-permission.sh
    destination: /home/ec2-user/apps/hello-word/
  - source: ./start-addition-service.sh
    destination: /home/ec2-user/apps/hello-word/
  - source: ./appspec.yml
    destination: /home/ec2-user/apps/hello-word/
hooks:
  AfterInstall:
    - location: change-file-permission.sh
      runas: root
  ApplicationStart:
    - location: start-addition-service.sh
      runas: root