version: 0.0
os: linux
files:
  - source: ./
    destination: change-file-permission.sh
  - source: ./
    destination: start-addition-service.sh
hooks:
  AfterInstall:
    - location: change-file-permission.sh
      runas: root
  ApplicationStart:
    - location: start-addition-service.sh
      runas: root